// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEtGICZDRPL4VxE4sjnQO4grN0qQGcoIA',
    appId: '1:752575815746:web:db85ecd3675595c4484ddb',
    messagingSenderId: '752575815746',
    projectId: 'test-276ae',
    authDomain: 'test-276ae.firebaseapp.com',
    storageBucket: 'test-276ae.appspot.com',
    measurementId: 'G-P65QW1TYX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsvTFsNVfwZZyxG4rTqWH7hYPcJRpFezU',
    appId: '1:752575815746:android:6a3dd4c9a75d53d5484ddb',
    messagingSenderId: '752575815746',
    projectId: 'test-276ae',
    storageBucket: 'test-276ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4eahY9eUiIOkh69uMXHWhtLPD5xxT-MM',
    appId: '1:752575815746:ios:49ce1afe08602aad484ddb',
    messagingSenderId: '752575815746',
    projectId: 'test-276ae',
    storageBucket: 'test-276ae.appspot.com',
    androidClientId: '752575815746-lt1ue0me03uuhef1lonn2r4mg43527ck.apps.googleusercontent.com',
    iosClientId: '752575815746-lfjc5dqm6vfr8dqcctt2hlo93jklks5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4eahY9eUiIOkh69uMXHWhtLPD5xxT-MM',
    appId: '1:752575815746:ios:49ce1afe08602aad484ddb',
    messagingSenderId: '752575815746',
    projectId: 'test-276ae',
    storageBucket: 'test-276ae.appspot.com',
    androidClientId: '752575815746-lt1ue0me03uuhef1lonn2r4mg43527ck.apps.googleusercontent.com',
    iosClientId: '752575815746-lfjc5dqm6vfr8dqcctt2hlo93jklks5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );
}
