import 'package:flutter/material.dart';

class ColorResources {
  static const Color bluegreen = Color(0xff67C4A7);
  static const Color white = Color(0xffFFFFFF);
  static const Color blue1D3 = Color(0xff1D3A70);
  static const Color grey6B7 = Color(0xff6B7280);
  static const Color greyB3B = Color(0xffB3B7BB);
  static const Color black = Color(0xff000000);
  static const Color greyAEA = Color(0xffAEAEAE);
  static const Color greyF9F = Color(0xffF9FAFB);
  static const Color grey9CA = Color(0xff9CA3AF);
  static const Color greyE5E = Color(0xffE5E7EB);
  static const Color black0F1 = Color(0xff0F172A);
  static const Color green1DA = Color(0xff1DAB87);
  static const Color greyF1F = Color(0xffF1F1F1);
  static const Color green00B = Color(0xff00B428);
  static const Color redF53 = Color(0xffF53E02);
  static const Color whiteE1E = Color(0xffE1ECFF);
  static const Color green1B7 = Color(0xff1B732E);
  static const Color greyC1C = Color(0xffC1C1C1);
  static const Color greyF3F = Color(0xffF3F4F6);
  static const Color greyF6F = Color(0xffF6F7FA);
  static const Color greyEDE = Color(0xffEDEDED);
  static const Color redD90 = Color(0xffD90429);
  static const Color greyDEE = Color(0xffDEE4F0);
  static const Color whiteF0F = Color(0xffF0FCFF);
  static const Color black111 = Color(0xff111827);
  static const Color grey777 = Color(0xff777777);
  static const Color orangeFB9 = Color(0xffFB923C);
  static const Color purple4D5 = Color(0xff4D5DFA);
  static const Color whiteEDF = Color(0xffEDF6FF);
  static const Color pinkFFE = Color(0xffFFEDFF);
  static const Color purpleEDE = Color(0xffEDEFFF);
  static const Color greenFDF = Color(0xffEDFFF9);
  static const Color whiteD9F = Color(0xffD9E7F4);
  static const Color orangeFFE = Color(0xffFFEDED);
  static const Color greenEDF = Color(0xffEDFFEF);
  static const Color yellowFFF = Color(0xffFFFFED);
  static const Color purpleF2E = Color(0xffF2EDFF);
  static const Color greyE1E = Color(0xffE1E1E1);
}
